{{- range $name, $component := .Values.components }}
{{- if and $component.enabled $component.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app-template.componentFullname" (list $ $name) }}
  labels:
    {{- include "app-template.commonLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app-template.componentFullname" (list $ $name) }}
  minReplicas: {{ $component.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $component.autoscaling.maxReplicas | default 3 }}
  metrics:
    {{- if $component.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $component.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $component.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $component.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
